### ISSUE TITLE
[Bug] Reponse Templating for Path doesn't match while using Json stubbing

### ISSUE THREAD

**Issue by cool-mist** [tomakehurst/wiremock#1181]
As per [docs](https://github.com/tomakehurst/wiremock/blob/master/docs-v2/_docs/response-templating.md) `request.pathSegments.[x]` should pick the path segment at 'x+1' position. However, this doesn't work while **_stubbing requests using json_**.

What works though is `request.path.[x]`.

We should update the doc to reflect the same.  

Wiremock version : 2.24.1

**What I used that didn't work**
```
{
  "request": {
    "method": "GET",
    "urlPattern": "/proxy/.*/api/v1/applications/.*/executors"
  },
  "response": {
       "status" : 200,
       "bodyFileName" : "responses/apps/{{request.pathSegments.[1]}}.json"
   }
}
```

**What works after some modification**
```
{
  "request": {
    "method": "GET",
    "urlPattern": "/proxy/.*/api/v1/applications/.*/executors"
  },
  "response": {
       "status" : 200,
       "bodyFileName" : "responses/apps/{{request.path.[1]}}.json"
   }
}
```

**Comment by tomakehurst** [comment]
Can you elaborate what you mean by "doesn't work"? A failing test case that demonstrates this would be great.

**Comment by cool-mist** [comment]
Sure. By 'doesn't work', I wanted to mean request.pathSegments.[1] expands to an empty string. This leads to searching for the file responses/apps/.json

If I want to load and return the path.json, I had to use 'request.path.[1]' instead.

**Comment by tomakehurst** [comment]
The correct usage is `request.requestLine.pathSegments.[1]`. I've fixed the docs to reflect this now.

**Comment by pinkfear** [comment]
That fixed it for me too...
But the documentation at http://wiremock.org/docs/response-templating/ still shows 
> request.pathSegments.[<n>]- URL path segment (zero indexed) e.g. request.pathSegments.[2]

**Comment by bobble14988** [comment]
Yeah the docs haven't been updated at all
